### ISSUE TITLE
[Bug] Wont compile in the last version 

### ISSUE THREAD

**Issue by vinkla** [posthtml/posthtml-cli#155]
I'm running the latest version (0.2.11) and it wont compile the HTML for me. If I downgrade to version 0.2.10 it works. I've submitted my error message below:

```sh
posthtml -o output.html -i input.html
```

> (node:8401) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot convert undefined or null to object
(node:8401) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm running the latest version of Node.js and npm on macOS Sierra.

**Comment by GitScrum** [comment]
@vinkla Hi, thanks i know and create [PR](https://github.com/posthtml/posthtml/pull/201)

**Comment by GitScrum** [comment]
@vinkla Hi, now you can update to 0.2.12

**Comment by vinkla** [comment]
Thanks!
