### ISSUE TITLE
[fix]: Cannot use config file without json extension

### ISSUE THREAD

**Issue by CarlosJeurissen** [posthtml/posthtml-cli#255]
Config files without a json extension, for example ".posthtmlrc" can't be used. This is due to the use of require to fetch the config file.

Please consider replacing require with:
`JSON.parse(fs.readFileSync(argv.config, 'utf8'))`

Talking of which, the config file gets fetched once for each file you process. To solve this, please consider fetching the config file only once, like this:

`var cfgData = argv.config && JSON.parse(fs.readFileSync(argv.config, 'utf8'));`

and use it in the processing file like this:
`var cfg = cfgData ? Object.keys(cfgData) : [];`
and
`if (cfgData) {config = Object.assign(cfgData, config)}`

**Comment by GitScrum** [comment]
@CarlosJeurissen HI, hanks, I'll think, it may be PR ?
