### ISSUE TITLE
[perf]: change globby to fast-glob

### ISSUE THREAD

**Issue by GitScrum** [posthtml/posthtml-cli#260]
https://github.com/mrmlnc/fast-glob

**Comment by mrmlnc** [comment]
Please, don't forget set `bashNative` option to `[]` value :tada:

**Comment by mrmlnc** [comment]
Now `globby` used `fast-glob`. But `fast-glob` still faster :P

**Comment by GitScrum** [comment]
Thanks, how to use ‘bashNative’ ? I not find description in readme

**Comment by mrmlnc** [comment]
The `bashNative` option is deleted since`fast-glob@2`.
