### ISSUE TITLE
how to disable attributes reformatting ?

### ISSUE THREAD

**Issue by ctf0** [posthtml/posthtml-cli#297]
when loading the config even when its empty ex.
```
{
    "plugins": {}
}
```

posthtml will reformat the attributes from
```
<v-touch class="card"
    :class="test"
    @swiperight="cardSwipGesture"
    @swipeleft="cardSwipGesture"
    @swipeup="cardSwipGesture"
    @swipedown="cardSwipGesture">
```

to
```
<v-touch class="card" :class="test" @swiperight="cardSwipGesture" @swipeleft="cardSwipGesture" @swipeup="cardSwipGesture" @swipedown="cardSwipGesture">
```

> this doesn't happen if we omitted the config param ex.`posthtml file.html -o file.html`

1. is there a way to stop that ?
2. is there a a way to reverse the effect so we can put each attribute on a seperate line ?

**Comment by anikethsaha** [comment]
Not sure how to stop this as I think it cant be but the only thing is why would you want to make changes in the output file?
you can do changes in the input and generate output should not be changed manually. It should be changed programmatically like using plugins etc.

**Comment by ctf0** [comment]
what am trying to do is to format the file with plugins and save it back to the same file, like formatting on save

**Comment by Scrum** [comment]
reforming will always occur, because the parser parses and then collects and it does not know anything about the indentation in the tag

**Comment by ctf0** [comment]
can we extract this behavior to a plugin or a param maybe ?

**Comment by Scrum** [comment]
I think not, because this is parsing on the side `posthtml-parser`, perhaps as an option for `posthtml-parser`

**Comment by ctf0** [comment]
well, thats a bummer :cry:

**Comment by anikethsaha** [comment]
> what am trying to do is to format the file with plugins and save it back to the same file, like formatting on save

You cant do formatting on save with plugins. I think you need a custom renderer to do it !
But you will have less infor about the source code format from the previous.  It gives you AST and you output a html. Try writing a custom renderer.
