### ISSUE TITLE
Output html files are not nested

### ISSUE THREAD

**Issue by DiversityStudio** [posthtml/posthtml-cli#300]
I have this config:

`{
    "input": "src/views/**/*.html",
    "output": "dist/",
    "plugins": {
        "posthtml-modules": {
            "root": "./src/views/_components/",
            "initial": true
        },
        "htmlnano": {}
    }
}`

Where I expect this nested output:

`/dist/index.html
/dist/other/index.html
/dist/other/other/index.html`

But I get a flattened output of just:

`/dist/index.html`

Is the CLI not honouring the input's nested structure and mirroring this in the output?

Can you advise please, thank you.

**Comment by Scrum** [comment]
@DiversityStudio Hi, thank you for your message, this functionality is in progress, and wait for the release to finish.

**Comment by DiversityStudio** [comment]
Hi, thank you, great work on posthtml, super cool
