### ISSUE TITLE
Pass options.from to plugins

### ISSUE THREAD

**Issue by giuseppeg** [posthtml/posthtml-cli#303]
Hi folks, is there a way to get the `options.from` passed to plugins when using posthtml-cli?

**Comment by Scrum** [comment]
@giuseppeg Hi, if you are using CLI then you just need to indicate `posthtml inputFolder/**/*.html` or you can also specify the root directory `posthtml **/*.html -r inputFolder -o outputFolder`,  if using `posthtml.config.js` then you can independently adjust the root directory for `input` files.

```js
const path = require('path');
const inputRoot = path.resolve(__dirname, 'src');

module.exports = {
  input: `${inputRoot}/**/*.html`
}
```

**Comment by Scrum** [comment]
You can reopen the issue if I can help you with something in this matter.

**Comment by giuseppeg** [comment]
@Scrum I am using posthtml-cli and setting the `-r` option but the plugin is not receiving the filename that is being processed:

https://github.com/posthtml/posthtml-cli/blob/793a24876a4e9a8e96baa3a15d835170a47c282c/src/cli.js#L96

Every time we visit a file we should pass `options.from` I think

```js
.then(html => Promise.resolve(posthtml(plugins).process(html, { ...config.options, from: file } )))
```

**Comment by Scrum** [comment]
>  I am using posthtml-cli and setting the -r option but the plugin is not receiving the filename that is being processed:

@giuseppeg Thanks for the find, it looks like a bug

**Comment by giuseppeg** [comment]
@Scrum thanks! It seems that you released a fix, how can I access `from` in the plugin now?

**Comment by Scrum** [comment]
> @Scrum thanks! It seems that you released a fix, how can I access `from` in the plugin now?

ohh, I completely forgot about this option. I will plan it in the next release
