### ISSUE TITLE
posthtml options

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-cli#306]
Hi @Scrum.
Thank you very much. This does work.

Could you please tell me how could I achieve the same functionality but with plugins in the config file (`.posthtmlrc`)?

_Originally posted by @VladimirMikulic in https://github.com/posthtml/posthtml/issues/329#issuecomment-673316646_

**Comment by Scrum** [comment]
@VladimirMikulic Unfortunately, this functionality is not available, I made it a separate task and soon I will implement it

**Comment by Scrum** [comment]
@VladimirMikulic publish v0.7.1

**Comment by VladimirMikulic** [comment]
@Scrum fixed in a snap! Wow!
I appreciate that very much.

I tried it now, but it seems that it is not picking up the config file.

**Comment by Scrum** [comment]
```{
  input: 'test/fixtures/by-config/options/input.html',
  output: 'test/expected/by-config/options/output.html',
  options: {
    directives: [{name: '?php', start: '<', end: '>'}]
  }
}```
