### ISSUE TITLE
I tried 0.7.3 and the cli doesn't work yet.

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-cli#317]
I tried 0.7.3 and the cli doesn't work yet. Here is how I use it:

```
posthtml "some/inputFolder/**/*.html" "!**/some/outFolder/**" -r some/inputFolder -a -o some/outFolder
```
(notice the glob patterns are quoted so that the shell doesn't expand them).

In order for fast-glob to grab those files you shouldn't resolve the path to absolute - you should remove the following line 

https://github.com/posthtml/posthtml-cli/blob/461615213ccd1bb66817582f9f42572d34946cfb/src/cfg-resolve.js#L32

_Originally posted by @giuseppeg in https://github.com/posthtml/posthtml-cli/issues/313#issuecomment-675449428_

**Comment by Scrum** [comment]
@giuseppeg Hello,

> (notice the glob patterns are quoted so that the shell doesn't expand them).

The use of quotes is due to the fact that when using a pattern like `*`, the `nodejs` tries to resolve this by returning all the file matches from the `process.cwd`.

**`test.js`**
```js
console.log(process.argv.slice(2));
```
**`you terminal`**
```bash
$ node test.js *
```
Such a script will work correctly.
```bash
node lib/cli.js "fixtures/**/*.html" -r test -a -o outFolder
```

> In order for fast-glob to grab those files you shouldn't resolve the path to absolute - you should remove the following line

fast-glob works correctly, the problem lies in `"!**/some/outFolder/**"` and I'm trying to understand her

```bash
node lib/cli.js "fixtures/**/*.html" "!input-nesting" -r test -o outFolder  
```
transform to 
```bash
node lib/cli.js "fixtures/**/*.html" "nesting" -r test -o outFolder
```
and try execute
```bash
zsh: event not found: input
```

**Comment by giuseppeg** [comment]
@Scrum I use bash instead of zsh and the CLI received the pattern just fine. When quoted it is just a string `"!**/some/outFolder/**"` and the shell won't expand it. Then fast-glob will find it just fine - that was the case with an older version of posthtml-cli before you changed it to resolve them to absolute paths

**Comment by Scrum** [comment]
> What was the reason to prefix the patters with the absolute path?

For a correct resolution relative to the root directory

**Comment by giuseppeg** [comment]
ah ok! I was indeed doing this in my own script and that messed things up
