### ISSUE TITLE
Not compiling in newest version

### ISSUE THREAD

**Issue by The-Podsiadly** [posthtml/posthtml-cli#323]
PostHTML does not compile HTML files when using the CLI.

### `Details`
Had to revert to versions:
```
"posthtml": "^0.12.0",
"posthtml-cli": "^0.5.2",
"posthtml-modules": "^0.4.2"
```

## `Error (Logs|Stacks)`
```
PS C:\Users\XXX> npm run build:html

> posthtml -c posthtml.json
```

### `Reproduction (Code)`
My `package.json` looked this this:
```
{
  "scripts": {
    "build:html": "posthtml -c posthtml.json",
    "watch:html": "onchange \"src/views\" -- npm run build:html",
  },
  "devDependencies": {
    "@babel/preset-env": "^7.8.4",
    "autoprefixer": "^9.7.4",
    "babel-loader": "^8.0.6",
    "browser-sync": "^2.26.12",
    "eslint": "^6.8.0",
    "eslint-loader": "^3.0.3",
    "htmlnano": "^0.2.6",
    "imagemin-cli": "^5.1.0",
    "node-sass": "^4.14.1",
    "npm-run-all": "^4.1.5",
    "onchange": "^7.0.2",
    "postcss-cli": "^7.1.2",
    "posthtml": "^0.13.3",
    "posthtml-cli": "^0.7.5",
    "posthtml-modules": "^0.6.2",
    "stylelint": "^13.7.1",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  }
}
```

And my `posthtml.json` looked like this:
```
{
    "input": "src/views/*.html",
    "output": "dist",
    "plugins": {
        "posthtml-modules": {
            "root": "./src/views",
            "initial": true
        },
        "htmlnano": {}
    }
}

```

### `Environment`
|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|Windows 19042.508|[v14.5.0]|[npm 6.14.5]|[0.13.3]|

**Comment by Scrum** [comment]
> The problem is is that no error showed showed. It ran the command but didn't compile an html file into the `dist/` folder. I tried debugging it, and still got no logs related to PostHTML.
> 
> Were you able to get the files to compile into a `dist/` using the latest versions of PostHTML, PostHTML-cli, and PostHTML-modules?

Yes, you can be sure by cloning the project https://github.com/test-issues/posthtml-cli-issue-333

**Comment by The-Podsiadly** [comment]
I ran both `npm run build` and `npx posthtml -c posthtml.json ` and didn't receive an output in the terminal and it didn't compile a new an `index.html` in the `dist/` folder.

**Comment by Scrum** [comment]
hmm, previously the problem may be due to the used `window`.  I'll try to think of something how to test it

**Comment by The-Podsiadly** [comment]
I decided to work back and revert to older versions for each of the 3 posthtml packages while keeping 2 of 3 at the latest version. These package versions worked:
```
PostHTML@0.13.3
PostHTML-CLI@0.6.0
PostHTML-Modules@0.6.2
```
In my opinion, on my system, `PostHTML-CLI@0.7.x` might be broken on my system. Let me upgrade my NodeJS [14.11.0] and npm [6.14.8].

**Comment by patorpey** [comment]
I have experienced the same behavior of no output without any error using the recent releases. I also rolled back one release at a time (of just posthtml-cli) and found that it works for posthtml-cli@0.7.1 but not 0.7.2 and later.

Environment:
node v12.16.1, Windows 7 Ent. SP1

**Comment by Scrum** [comment]
@patorpey @The-Podsiadly thanks for the find, this is related to the package [fast-glob](https://github.com/mrmlnc/fast-glob/issues/289)

**Comment by The-Podsiadly** [comment]
@Scrum How did you figure that out?

**Comment by Scrum** [comment]
> @Scrum How did you figure that out?

I had to do a lot of tests using github actions https://github.com/inside-demo/fast-glob-demo/pull/2/checks?check_run_id=1144028881

see step  Run tests
